version 18.0
* Purpose: choropleth of the 2025 CBD-toll tip response by pickup zone.
* Inputs:  data/cells/zone_geometry.csv, ${DATA_CLEAN}/zone_panel.dta
* Outputs: ${FIGURES}/fig-map.pdf

* Where the transfer is generated: annualized extra tip dollars induced by
* the CBD toll, by pickup zone = (fee dollars charged on card trips) x rho.
use "${DATA_CLEAN}/zone_panel.dta", clear
keep if inrange(t, ym(2025,1), ym(2025,6))
gen double feepaid = n_card*mean_cbd
collapse (sum) feepaid n_card, by(pu cbdzone)
gen double dtip = feepaid*0.146*2/1000        // annualized, $000s
quietly sum dtip if cbdzone
di as result "Induced tips by zone, annualized ($000s):"
di as result "   CBD zones: mean " %8.1f r(mean) ", max " %8.1f r(max) ", n=" r(N)
quietly sum dtip if !cbdzone
di as result "   non-CBD:   mean " %8.1f r(mean) ", max " %8.1f r(max) ", n=" r(N)
quietly sum dtip
di as result "   citywide total: $" %8.0f r(sum) "k"
keep pu dtip cbdzone
save "${DATA_INT}/map_vals.dta", replace

* merge onto geometry
import delimited "${PROJECT_ROOT}/data/cells/zone_geometry.csv", clear varnames(1)
merge m:1 pu using "${DATA_INT}/map_vals.dta", keep(1 3) nogen
* quintile bins for shading
replace dtip = . if dtip <= 0
xtile q = dtip, nq(5)
replace q = 0 if missing(dtip)
sort pu part
* plot: one area per zone, shaded by quintile
levelsof pu, local(zs)
local cmd ""
foreach z of local zs {
    quietly sum q if pu == `z'
    local qq = r(mean)
    if `qq' == 1 local c "227 226 240"
    if `qq' == 2 local c "180 178 220"
    if `qq' == 3 local c "130 128 195"
    if `qq' == 4 local c "70 70 160"
    if `qq' == 5 local c "20 20 110"
    if `qq' == 0 local c "235 235 235"
    local cmd `"`cmd' (area lat lon if pu == `z', cmissing(n) nodropbase fcolor("`c'") lcolor(gs11) lwidth(vvthin))"'
}
twoway `cmd', aspectratio(1.25) legend(off) ///
    xtitle("") ytitle("") xlabel(none) ylabel(none) ///
    graphregion(color(white)) plotregion(lcolor(none)) ///
    note("Darker = more additional tip dollars generated by the 2025 congestion toll" ///
         "(fee dollars charged on card trips x estimated pass-through, annualized)." ///
         "Grey = zone generates none. Manhattan and inner boroughs.", size(vsmall))
graph export "${FIGURES}/fig-map.pdf", as(pdf) replace
